spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mybatis_plus?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: admin
logging:
  level:
    root: warn
    cn.springlearn.mybatis_plus.dao: trace
  pattern:
    console: '%p%m%n'